services:
  ai-server:
    build: ./ai_server
    env_file:
      - ./ai_server/.env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/../data
      - ./ai_server/storage:/app/storage
  backend-spring:
    build: ./backend_spring
    ports:
      - "8080:8080"
    environment:
      AI_SERVER_BASE_URL: http://ai-server:8000
    depends_on:
      - ai-server
